name: okeyee
version: 0.1.7
author: Egor Day <edaydev@gmail.com>
description: Keyboard events handling library
homepage: https://github.com/daydev/okeyee.git
dependencies:
  browser: any
  unittest: any
